<?php
/**
 * Admin Modal Component
 * Used for adding and editing records
 */
?>
<div id="adminModal" class="admin-modal">
    <div class="admin-modal-content">
        <div class="admin-modal-header">
            <h2 id="modalTitle">Add New Record</h2>
            <button type="button" class="admin-modal-close" id="closeModal">
                <span class="material-symbols-outlined">close</span>
            </button>
        </div>

        <form id="adminForm" class="admin-form">
            <div id="formFields" class="admin-form-fields">
                <!-- Fields will be generated by JavaScript -->
            </div>

            <div class="admin-form-actions">
                <button type="submit" class="admin-btn-primary" id="submitBtn">Save</button>
                <button type="button" class="admin-btn-secondary" id="cancelBtn">Cancel</button>
            </div>
        </form>
    </div>
</div>
